# https://github.com/KinNeko-De/sample-flutter-web-ci-cd-githubpages/blob/main/.github/workflows/cicd.yaml
# Thanks KinNeko-De for the original workflow
name: CI/CD for Flutter Web to GitHub Pages

on:
  push:

env:
  PATH_TO_APP : cell_pulse

jobs:
    ci:
      name: Continuous Integration
      runs-on: ubuntu-latest
      steps:
        - name: Clone repository
          uses: actions/checkout@v6
        - name: Set up Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable
            flutter-version-file: cell_pulse/pubspec.yaml # path to pubspec.yaml or .fvmrc or .fvm/fvm_config.json
        - run: flutter --version

        - name: Setup Pages
          id: pages
          uses: actions/configure-pages@v6

        - name: Install dependencies
          run: flutter pub get
          working-directory: ${{ env.PATH_TO_APP }}

        - name: Set short sha for build number
          id: vars
          run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

        - name: Build app for web
          run: flutter build web --build-number=${{ steps.vars.outputs.sha_short }} --base-href "${{ steps.pages.outputs.base_path }}/" --wasm
          working-directory: ${{ env.PATH_TO_APP }}

        # - name: Run tests
        #   run: flutter test
        #   working-directory: ${{ env.PATH_TO_APP }}

        - name: Upload artifact
          if: github.ref == 'refs/heads/master'
          uses: actions/upload-pages-artifact@v5
          with:
            path: ${{ env.PATH_TO_APP }}/build/web

    cd:
      name: Continuous Deployment
      needs: ci
      if: github.ref == 'refs/heads/master'
      runs-on: ubuntu-latest
      permissions:
        pages: write
        id-token: write
      environment:
        name: github-pages
        url: ${{ steps.deployment.outputs.page_url }}
      steps:
        - name: Deploy
          id: deployment
          uses: actions/deploy-pages@v5